FROM node:22-alpine:3.21

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4002

CMD [ "npm" , "run" , "dev" ]